version: "3.5"

services:
    api01: &api
        hostname: api01
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/app
        environment:
            - DB_HOSTNAME=postgresql://admin:123@db:5432/rinha
        ports:
            - "8001:8000"
        depends_on:
            - db
        deploy:
            resources:
                limits:
                    cpus: "0.55"
                    memory: "200MB"

    api02:
        <<: *api
        hostname: api02
        ports:
            - "8002:8000"

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api01
            - api02
        ports:
            - "9999:9999"
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: "30MB"

    db:
        image: postgres:latest
        hostname: db
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_USER=admin
            - POSTGRES_DB=rinha
        ports:
            - "5434:5432"
        command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
        deploy:
            resources:
                limits:
                    cpus: "0.3"
                    memory: "120MB"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    default:
        driver: bridge
        name: rinha-nginx-2024q1